/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

/**
 *
 * @author Cetecom
 */
public class MenuPrincipalClientes extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipalClientes
     */
    public MenuPrincipalClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        mnbMenu = new javax.swing.JMenuBar();
        mnuGestionarClientes = new javax.swing.JMenu();
        mniAgregarCliente = new javax.swing.JMenuItem();
        mniEditarCliente = new javax.swing.JMenuItem();
        mniEliminarCliente = new javax.swing.JMenuItem();
        mniListarClientes = new javax.swing.JMenuItem();
        mnuSalir = new javax.swing.JMenu();
        mniSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblTitulo.setText("Bienvenido al sistema de gestion de Clientes");

        lblDescripcion.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblDescripcion.setText("Seleccione alguna opcion");

        mnuGestionarClientes.setText("Gestionar Clientes");

        mniAgregarCliente.setText("Agregar");
        mniAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAgregarClienteActionPerformed(evt);
            }
        });
        mnuGestionarClientes.add(mniAgregarCliente);

        mniEditarCliente.setText("Editar");
        mniEditarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniEditarClienteActionPerformed(evt);
            }
        });
        mnuGestionarClientes.add(mniEditarCliente);

        mniEliminarCliente.setText("Eliminar");
        mniEliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniEliminarClienteActionPerformed(evt);
            }
        });
        mnuGestionarClientes.add(mniEliminarCliente);

        mniListarClientes.setText("Listar");
        mniListarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniListarClientesActionPerformed(evt);
            }
        });
        mnuGestionarClientes.add(mniListarClientes);

        mnbMenu.add(mnuGestionarClientes);

        mnuSalir.setText("Salir");

        mniSalir.setText("Salir");
        mniSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSalirActionPerformed(evt);
            }
        });
        mnuSalir.add(mniSalir);

        mnbMenu.add(mnuSalir);

        setJMenuBar(mnbMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(192, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblDescripcion)
                        .addGap(82, 82, 82)))
                .addGap(176, 176, 176))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDescripcion)
                .addContainerGap(199, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAgregarClienteActionPerformed
        AgregarCliente ag = new AgregarCliente();
        ag.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mniAgregarClienteActionPerformed

    private void mniListarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniListarClientesActionPerformed
        ListarClientes lc = new ListarClientes();
        lc.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mniListarClientesActionPerformed

    private void mniEditarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniEditarClienteActionPerformed
        EditarCliente ec = new EditarCliente();
        ec.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mniEditarClienteActionPerformed

    private void mniEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniEliminarClienteActionPerformed
        EliminarCliente dc = new EliminarCliente();
        dc.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mniEliminarClienteActionPerformed

    private void mniSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mniSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipalClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JMenuBar mnbMenu;
    private javax.swing.JMenuItem mniAgregarCliente;
    private javax.swing.JMenuItem mniEditarCliente;
    private javax.swing.JMenuItem mniEliminarCliente;
    private javax.swing.JMenuItem mniListarClientes;
    private javax.swing.JMenuItem mniSalir;
    private javax.swing.JMenu mnuGestionarClientes;
    private javax.swing.JMenu mnuSalir;
    // End of variables declaration//GEN-END:variables
}
